# Generated by Django 5.2.10 on 2026-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
