# Generated by Django 5.2.10 on 2026-01-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='logo',
        ),
    ]
