# Generated by Django 5.2.10 on 2026-01-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoice_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Fully Paid'),
        ),
    ]
